// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/gin-gonic/gin"
	"sass-scaffold/internal/user/adapters"
	"sass-scaffold/internal/user/handler"
	"sass-scaffold/internal/user/service"
)

// Injectors from wire.go:

func InitV1(r *gin.RouterGroup) func() {
	userRepository := adapters.NewPSQLUserRepository()
	tokenCache := adapters.NewRedisTokenCache()
	tokenService := service.NewTokenService(tokenCache, userRepository)
	userService := service.NewUserService(userRepository, tokenService)
	httpHandler := handler.NewHttpHandler(userService)
	v := RegisterV1(r, httpHandler)
	return v
}
