// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

var TableNames = struct {
	Plans             string
	ProjectMembers    string
	Projects          string
	TeamMembers       string
	Teams             string
	UsageStats        string
	UserSubscriptions string
	Users             string
}{
	Plans:             "plans",
	ProjectMembers:    "project_members",
	Projects:          "projects",
	TeamMembers:       "team_members",
	Teams:             "teams",
	UsageStats:        "usage_stats",
	UserSubscriptions: "user_subscriptions",
	Users:             "users",
}
